// This file is regenerated by NanoFL on every publish.

/// <reference types='nanofl-ts' />

import * as linked from './linked-classes';

export namespace base
{
	export class MyButton extends nanofl.Button
	{
		constructor() {
			super(nanofl.Player.library.getItem("MainButton"));
		}
	}
}
