/******/ (() => { // webpackBootstrap
/******/ 	// runtime can't be in strict mode because a global variable is assign and maybe created.
/******/ 	var __webpack_modules__ = ({

/***/ "./src/Game.ts":
/*!*********************!*\
  !*** ./src/Game.ts ***!
  \*********************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   Game: () => (/* binding */ Game)
/* harmony export */ });
/* harmony import */ var _autogenerated_base__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./autogenerated/base */ "./src/autogenerated/base.ts");
/* harmony import */ var _autogenerated_Sounds__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./autogenerated/Sounds */ "./src/autogenerated/Sounds.ts");
/* harmony import */ var _McBucket__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ./McBucket */ "./src/McBucket.ts");



class Game extends _autogenerated_base__WEBPACK_IMPORTED_MODULE_0__.base.Game {
    constructor() {
        super(...arguments);
        this.level = 0;
        this.buckets = new Array();
        this.carry = null;
        this.action = 0; // what to do with "carry" if user release it
        // 0 - nothing
        // 1-4 - see gameMode
        this.fallTo = null;
        this.gameMode = 0; // 0 - waiting to user
        // 1 - tansfuse water from "carry" into "fallTo"
        // 2 - filling "carry" from tap
        // 3 - falling out from carry to trash
        // 4 - moving bucket to floor
        this.tapWaiting = 0; // tick counter
        this.fillBeforeTrash = 0;
    }
    get scene() { return this.parent; }
    init() {
        this.scene.stop();
        this.level = this.scene.level;
        this.scene.tfLevel.text = this.level + "";
        switch (this.level) {
            case 1:
                this.scene.tfTask.text = "You need to measure 4 litres of water,\nusing two buckets of 5 and 7 litres.\nUse barrel (at the right) for filling buckets.\nTo make buckets empty, use trash (at the left).";
                this.buckets.push(this.addChild(new _McBucket__WEBPACK_IMPORTED_MODULE_2__.McBucket(5, 220)));
                this.buckets.push(this.addChild(new _McBucket__WEBPACK_IMPORTED_MODULE_2__.McBucket(7, 320)));
                break;
            case 2:
                this.scene.tfTask.text = "You need to measure 1 liter of water.";
                this.buckets.push(this.addChild(new _McBucket__WEBPACK_IMPORTED_MODULE_2__.McBucket(3, 180)));
                this.buckets.push(this.addChild(new _McBucket__WEBPACK_IMPORTED_MODULE_2__.McBucket(6, 280)));
                this.buckets.push(this.addChild(new _McBucket__WEBPACK_IMPORTED_MODULE_2__.McBucket(8, 380)));
                break;
            case 3:
                this.scene.tfTask.text = "You need to measure 1 liter of water.";
                this.buckets.push(this.addChild(new _McBucket__WEBPACK_IMPORTED_MODULE_2__.McBucket(3, 220)));
                this.buckets.push(this.addChild(new _McBucket__WEBPACK_IMPORTED_MODULE_2__.McBucket(5, 320)));
                break;
            case 4:
                this.scene.tfTask.text = "You need to got 1 liter of water in any two buckets.";
                this.buckets.push(this.addChild(new _McBucket__WEBPACK_IMPORTED_MODULE_2__.McBucket(3, 180)));
                this.buckets.push(this.addChild(new _McBucket__WEBPACK_IMPORTED_MODULE_2__.McBucket(4, 280)));
                this.buckets.push(this.addChild(new _McBucket__WEBPACK_IMPORTED_MODULE_2__.McBucket(6, 380)));
                break;
            case 5:
                this.scene.tfTask.text = "You need to got 6 litres of water in bigger bucket,\n4 liters in 5-bucket and 4 litres in 8-bucket.";
                this.buckets.push(this.addChild(new _McBucket__WEBPACK_IMPORTED_MODULE_2__.McBucket(3, 180)));
                this.buckets.push(this.addChild(new _McBucket__WEBPACK_IMPORTED_MODULE_2__.McBucket(5, 250)));
                this.buckets.push(this.addChild(new _McBucket__WEBPACK_IMPORTED_MODULE_2__.McBucket(8, 320)));
                this.buckets.push(this.addChild(new _McBucket__WEBPACK_IMPORTED_MODULE_2__.McBucket(12, 400)));
                break;
            case 6:
                this.scene.tfTask.text = "You need to got 2 liter of water in any three buckets.";
                this.buckets.push(this.addChild(new _McBucket__WEBPACK_IMPORTED_MODULE_2__.McBucket(3, 180)));
                this.buckets.push(this.addChild(new _McBucket__WEBPACK_IMPORTED_MODULE_2__.McBucket(3, 250)));
                this.buckets.push(this.addChild(new _McBucket__WEBPACK_IMPORTED_MODULE_2__.McBucket(8, 320)));
                this.buckets.push(this.addChild(new _McBucket__WEBPACK_IMPORTED_MODULE_2__.McBucket(11, 400)));
                break;
            case 7:
                this.scene.tfTask.text = "You need to got 1 liter of water in any two buckets..";
                this.buckets.push(this.addChild(new _McBucket__WEBPACK_IMPORTED_MODULE_2__.McBucket(2, 180)));
                this.buckets.push(this.addChild(new _McBucket__WEBPACK_IMPORTED_MODULE_2__.McBucket(3, 280)));
                this.buckets.push(this.addChild(new _McBucket__WEBPACK_IMPORTED_MODULE_2__.McBucket(9, 380)));
                break;
            case 8:
                this.scene.tfTask.text = "You need to got 1 liter of water in small three buckets.";
                this.buckets.push(this.addChild(new _McBucket__WEBPACK_IMPORTED_MODULE_2__.McBucket(5, 180)));
                this.buckets.push(this.addChild(new _McBucket__WEBPACK_IMPORTED_MODULE_2__.McBucket(7, 250)));
                this.buckets.push(this.addChild(new _McBucket__WEBPACK_IMPORTED_MODULE_2__.McBucket(9, 320)));
                this.buckets.push(this.addChild(new _McBucket__WEBPACK_IMPORTED_MODULE_2__.McBucket(11, 400)));
                break;
            case 9:
                this.scene.tfTask.text = "You need to fill buckets on increase:\nsmallest bust be empty, next must contain 1 liter,\nnext - 2 litres and bigger - 3 litres.";
                this.buckets.push(this.addChild(new _McBucket__WEBPACK_IMPORTED_MODULE_2__.McBucket(7, 180)));
                this.buckets.push(this.addChild(new _McBucket__WEBPACK_IMPORTED_MODULE_2__.McBucket(11, 250)));
                this.buckets.push(this.addChild(new _McBucket__WEBPACK_IMPORTED_MODULE_2__.McBucket(13, 320)));
                this.buckets.push(this.addChild(new _McBucket__WEBPACK_IMPORTED_MODULE_2__.McBucket(17, 400)));
                break;
            case 10:
                this.scene.tfTask.text = "You must to got 18 litres in 19-bucket and 5 litres in 6-bucket.";
                this.buckets.push(this.addChild(new _McBucket__WEBPACK_IMPORTED_MODULE_2__.McBucket(2, 180)));
                this.buckets.push(this.addChild(new _McBucket__WEBPACK_IMPORTED_MODULE_2__.McBucket(6, 280)));
                this.buckets.push(this.addChild(new _McBucket__WEBPACK_IMPORTED_MODULE_2__.McBucket(19, 380)));
                break;
        }
    }
    onEnterFrame() {
        switch (this.gameMode) {
            case 0:
                if (this.checkWin()) {
                    this.scene.level++;
                    this.scene.gotoAndStop("Win");
                }
                break;
            case 1: // transfuse water from current bucket to another
                this.fallTo.activate(false);
                if (this.carry.fallProcessStep(this.carryDX, this.carryDY)) {
                    this.gameMode = 0;
                    this.selectAction();
                }
                break;
            case 2: // filling bucket from tap
                if (this.carry.getFill() < this.carry.total) {
                    if (this.scene.mcTap.currentFrame != 2)
                        this.scene.mcTap.gotoAndStop(2);
                    this.tapWaiting++;
                    if (this.tapWaiting % 10 == 9) {
                        this.carry.setFill(this.carry.getFill() + 1);
                        _autogenerated_Sounds__WEBPACK_IMPORTED_MODULE_1__.Sounds.tap();
                        _autogenerated_Sounds__WEBPACK_IMPORTED_MODULE_1__.Sounds.water();
                    }
                }
                else // bucket is full
                 {
                    this.scene.mcTap.gotoAndStop(0);
                    if (this.carry.moveStepTo(new createjs.Point(this.stage.mouseX + this.carryDX, this.stage.mouseY + this.carryDY), 10)) {
                        this.tapWaiting = 0;
                        this.gameMode = 0;
                        this.selectAction();
                    }
                }
                break;
            case 3: // fall out to trash
                if (this.carry.fallProcessStep(this.carryDX, this.carryDY)) {
                    this.gameMode = 0;
                    this.selectAction();
                }
                else {
                    if (this.fillBeforeTrash > 0 && this.carry.getFill() < this.fillBeforeTrash) {
                        this.fillBeforeTrash = this.carry.getFill();
                        _autogenerated_Sounds__WEBPACK_IMPORTED_MODULE_1__.Sounds.trash();
                    }
                }
                break;
            case 4: // moving bucket to the ground
                if (this.carry.moveStepTo(new createjs.Point(this.carry.x, 345), 6)) {
                    this.carry = null;
                    this.gameMode = 0;
                    this.selectAction();
                }
                break;
        }
    }
    onMouseDown(e) {
        if (this.gameMode != 0)
            return;
        if (this.carry == null) // nothing carried
         {
            for (let i = 0; i < this.buckets.length; i++) {
                var pos = this.buckets[i].globalToLocal(e.stageX, e.stageY);
                if (this.buckets[i].hitTest(pos.x, pos.y)) {
                    this.carry = this.buckets[i];
                    this.carryDX = this.buckets[i].x - e.stageX;
                    this.carryDY = this.buckets[i].y - e.stageY;
                    // move bucket to the front
                    for (let j = 0; j < this.buckets.length; j++) {
                        if (this.getChildIndex(this.buckets[j]) > this.getChildIndex(this.carry)) {
                            this.swapChildren(this.buckets[j], this.carry);
                        }
                    }
                    break;
                }
            }
        }
        else // user have bucket
         {
            this.gameMode = this.action;
            if (this.gameMode == 1) {
                this.carry.startFallToProcess(this.fallTo);
            }
            else if (this.gameMode == 2) {
                this.tapWaiting = 0;
                this.carry.x = this.scene.mcTap.x;
            }
            else if (this.gameMode == 3) {
                this.fillBeforeTrash = this.carry.getFill();
                this.carry.startFallToProcess(this.scene.mcTrash);
            }
        }
    }
    onMouseUp(e) {
        if (this.gameMode != 0)
            return;
    }
    onMouseMove(e) {
        if (this.gameMode != 0)
            return;
        this.selectAction();
        if (this.carry != null) {
            this.carry.x = e.stageX + this.carryDX;
            this.carry.y = e.stageY + this.carryDY;
        }
    }
    selectAction() {
        this.action = 0;
        if (this.carry == null)
            return;
        var carryNeckPos = this.carry.getNeckPos();
        // want to fill from tap?
        if (Math.abs(carryNeckPos.x - this.scene.mcTap.x) < this.carry.scaleX * 8
            && carryNeckPos.y - this.scene.mcTap.y > -5
            && carryNeckPos.y - this.scene.mcTap.y < 40) {
            this.action = 2;
            this.scene.mcTap.gotoAndStop(1);
            return;
        }
        this.scene.mcTap.gotoAndStop(0);
        // want to fall out to trash?
        if (this.carry.x < 165 && this.carry.y <= 350) {
            this.action = 3;
            this.scene.mcTrash.gotoAndStop(1);
            return;
        }
        this.scene.mcTrash.gotoAndStop(0);
        // want to transfuse to another bucket?
        var bucket = this.findNearestBucket();
        if (this.carry.getTransformedBounds().intersects(bucket.getTransformedBounds())) {
            this.action = 1;
            this.fallTo = bucket;
            bucket.activate(true);
            for (const bucket of this.buckets)
                if (bucket != this.fallTo)
                    bucket.activate(false);
        }
        else {
            for (const bucket of this.buckets)
                bucket.activate(false);
        }
        // want to release bucket (move to floor)
        if (this.action == 0) {
            this.action = 4;
        }
    }
    findNearestBucket() {
        var bestBot = null;
        var bestDist = 1e10;
        for (const b of this.buckets) {
            if (b == this.carry)
                continue;
            var dx = this.carry.x - b.x;
            var dy = this.carry.y - b.y;
            var dist = Math.sqrt(dx * dx + dy * dy);
            if (dist < bestDist) {
                bestBot = b;
                bestDist = dist;
            }
        }
        return bestBot;
    }
    checkWin() {
        switch (this.level) {
            case 1: return this.buckets[0].getFill() == 4 || this.buckets[1].getFill() == 4;
            case 2: return this.buckets[0].getFill() == 1 || this.buckets[1].getFill() == 1 || this.buckets[2].getFill() == 1;
            case 3: return this.buckets[0].getFill() == 1 || this.buckets[1].getFill() == 1;
            case 4: return this.buckets.filter(bucket => bucket.getFill() == 1).length >= 2;
            case 5: return this.buckets[1].getFill() == 4 && this.buckets[2].getFill() == 4 && this.buckets[3].getFill() == 6;
            case 6: return this.buckets.filter(bucket => bucket.getFill() == 2).length >= 3;
            case 7: return this.buckets.filter(bucket => bucket.getFill() == 1).length >= 2;
            case 8: return this.buckets[0].getFill() == 1 && this.buckets[1].getFill() == 1 && this.buckets[2].getFill() == 1;
            case 9: return this.buckets[0].getFill() == 0 && this.buckets[1].getFill() == 1 && this.buckets[2].getFill() == 2 && this.buckets[3].getFill() == 3;
            case 10: return this.buckets[1].getFill() == 5 && this.buckets[2].getFill() == 18;
        }
        return false;
    }
}


/***/ }),

/***/ "./src/McBucket.ts":
/*!*************************!*\
  !*** ./src/McBucket.ts ***!
  \*************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   McBucket: () => (/* binding */ McBucket)
/* harmony export */ });
/* harmony import */ var _autogenerated_base__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./autogenerated/base */ "./src/autogenerated/base.ts");
/* harmony import */ var _autogenerated_Sounds__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./autogenerated/Sounds */ "./src/autogenerated/Sounds.ts");


class McBucket extends _autogenerated_base__WEBPACK_IMPORTED_MODULE_0__.base.McBucket {
    constructor(total, x) {
        super();
        this.fallProcessPhase = 0; // 0 - nothing to do
        // 1 - moving to preffered position
        // 2 - rotation forward
        // 3 - waiting water to fall out
        // 4 - rotation backward
        // 5 - moving to mouse position
        this.fillProcessDest = null;
        this.fillProcessFallFrame = 0;
        this.fill = 0;
        this.total = total;
        this.x = x;
        this.y = 345;
        this.scaleX = this.scaleY = Math.sqrt(total) * 40 / 100;
        this.setFill(0);
        this.activate(false);
    }
    getFill() { return this.fill; }
    setFill(v) {
        this.fill = v;
        this.tfLabel.text = this.fill + "/" + this.total;
        this.gotoAndStop(Math.round(this.fill / this.total * 100));
    }
    getNeckPos() {
        return new createjs.Point(this.x + this.mcNeck.x * this.scaleX, this.y + this.mcNeck.y * this.scaleY);
    }
    activate(act) {
        this.mcForeColor.visible = act;
    }
    fallToBucket(dest) {
        var freeDest = dest.total - dest.fill;
        if (freeDest > this.fill) {
            dest.setFill(dest.fill + this.fill);
            this.setFill(0);
        }
        else {
            dest.setFill(dest.total);
            this.setFill(this.fill - freeDest);
        }
    }
    startFallToProcess(dest) {
        if (this.fallProcessPhase != 0) {
            console.log("StartFallProcess error 1");
            return;
        }
        this.fallProcessPhase = 1;
        this.fillProcessDest = dest;
        this.fillProcessFallFrame = 0;
    }
    /**
     * Must be called on every frame while water falling.
     * @param mouseDX X offset for last step
     * @param mouseDY Y offset for last step
     * @returns Falling finished?
     */
    fallProcessStep(mouseDX, mouseDY) {
        if (this.fallProcessPhase == 0)
            return true;
        if (this.fallProcessPhase == 1) {
            var destNeck = this.fillProcessDest.getNeckPos();
            var b = this.mcBox.getBounds();
            var mustPos = new createjs.Point(destNeck.x + b.height * this.scaleY, destNeck.y);
            if (this.moveStepTo(mustPos, 6))
                this.fallProcessPhase++;
        }
        else if (this.fallProcessPhase == 2) {
            if (this.fill == 0 || this.fillProcessDest.getFill() == this.fillProcessDest.total)
                this.fallProcessPhase++;
            else {
                if (this.rotation > -90)
                    this.rotation -= 4;
                else
                    this.fallProcessPhase++;
            }
        }
        else if (this.fallProcessPhase == 3) {
            if (this.fill == 0 || this.fillProcessDest.getFill() == this.fillProcessDest.total)
                this.fallProcessPhase++;
        }
        else if (this.fallProcessPhase == 4) {
            if (this.rotation < 0)
                this.rotation += 4;
            else
                this.fallProcessPhase++;
        }
        else if (this.fallProcessPhase == 5) {
            var r = this.moveStepTo(new createjs.Point(this.stage.mouseX + mouseDX, this.stage.mouseY + mouseDY), 10);
            if (r == true)
                this.fallProcessPhase = 0;
            return r;
        }
        if ((this.fallProcessPhase == 2 && this.rotation < -40) || this.fallProcessPhase == 3) {
            this.fillProcessFallFrame++;
            if (this.fillProcessFallFrame % 7 == 6) {
                if (this.fill > 0 && this.fillProcessDest.getFill() < this.fillProcessDest.total) {
                    this.setFill(this.fill - 1);
                    this.fillProcessDest.setFill(this.fillProcessDest.getFill() + 1);
                    _autogenerated_Sounds__WEBPACK_IMPORTED_MODULE_1__.Sounds.water();
                }
            }
        }
        return false;
    }
    moveStepTo(dest, step) {
        var dx = dest.x - this.x;
        var dy = dest.y - this.y;
        var len = Math.sqrt(dx * dx + dy * dy);
        if (len < step) {
            this.x = dest.x;
            this.y = dest.y;
            return true;
        }
        else {
            this.x += dx / len * step;
            this.y += dy / len * step;
            return false;
        }
    }
}


/***/ }),

/***/ "./src/McTrash.ts":
/*!************************!*\
  !*** ./src/McTrash.ts ***!
  \************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   McTrash: () => (/* binding */ McTrash)
/* harmony export */ });
/* harmony import */ var _autogenerated_base__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./autogenerated/base */ "./src/autogenerated/base.ts");

class McTrash extends _autogenerated_base__WEBPACK_IMPORTED_MODULE_0__.base.McTrash {
    constructor() {
        super(...arguments);
        this.total = 100000;
    }
    getFill() { return 0; }
    setFill(v) { }
    getNeckPos() { return new createjs.Point(this.x, this.y); }
}


/***/ }),

/***/ "./src/MusicButton.ts":
/*!****************************!*\
  !*** ./src/MusicButton.ts ***!
  \****************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   MusicButton: () => (/* binding */ MusicButton)
/* harmony export */ });
/* harmony import */ var _autogenerated_base__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./autogenerated/base */ "./src/autogenerated/base.ts");
/* harmony import */ var _autogenerated_Sounds__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./autogenerated/Sounds */ "./src/autogenerated/Sounds.ts");


class MusicButton extends _autogenerated_base__WEBPACK_IMPORTED_MODULE_0__.base.MusicButton {
    init() {
        this.cursor = "pointer";
        this.musicOn();
    }
    onMouseUp(e) {
        if (this.getBounds().contains(e.localX, e.localY)) {
            if (this.currentFrame == 1)
                this.musicOn();
            else
                this.musicOff();
        }
    }
    musicOn() {
        this.gotoAndStop(0);
        this.soundLoop = new nanofl.SeamlessSoundLoop(_autogenerated_Sounds__WEBPACK_IMPORTED_MODULE_1__.Sounds.music());
        this.addEventListener("removed", () => this.soundLoop.stop());
    }
    musicOff() {
        this.gotoAndStop(1);
        this.soundLoop.stop();
    }
}


/***/ }),

/***/ "./src/Scene.ts":
/*!**********************!*\
  !*** ./src/Scene.ts ***!
  \**********************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   Scene: () => (/* binding */ Scene)
/* harmony export */ });
/* harmony import */ var _autogenerated_base__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./autogenerated/base */ "./src/autogenerated/base.ts");

class Scene extends _autogenerated_base__WEBPACK_IMPORTED_MODULE_0__.base.Scene {
    constructor() {
        super(...arguments);
        this.initFrame = null;
        this.level = 1;
    }
    onEnterFrame() {
        var _a, _b, _c, _d;
        if (this.currentFrame != this.initFrame) {
            this.initFrame = this.currentFrame;
            (_a = this.btGotoGame) === null || _a === void 0 ? void 0 : _a.addEventListener("click", () => this.gotoAndStop("Game"));
            (_b = this.btRules) === null || _b === void 0 ? void 0 : _b.addEventListener("click", () => this.gotoAndStop("Rules"));
            (_c = this.btGotoOrigin) === null || _c === void 0 ? void 0 : _c.addEventListener("click", () => this.gotoAndStop("Origin"));
            (_d = this.btNextLevel) === null || _d === void 0 ? void 0 : _d.addEventListener("click", () => this.gotoAndStop("Game"));
        }
    }
}


/***/ }),

/***/ "./src/autogenerated/Sounds.ts":
/*!*************************************!*\
  !*** ./src/autogenerated/Sounds.ts ***!
  \*************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   Sounds: () => (/* binding */ Sounds)
/* harmony export */ });
// This file is autogenerated by NanoFL
/// <reference types='nanofl-ts' />
class Sounds {
    static bucket(interrupt, delay, offset, loop, volume, pan) { return createjs.Sound.play("bucket", interrupt, delay, offset, loop, volume, pan); }
    static music(interrupt, delay, offset, loop, volume, pan) { return createjs.Sound.play("music", interrupt, delay, offset, loop, volume, pan); }
    static tap(interrupt, delay, offset, loop, volume, pan) { return createjs.Sound.play("tap", interrupt, delay, offset, loop, volume, pan); }
    static trash(interrupt, delay, offset, loop, volume, pan) { return createjs.Sound.play("trash", interrupt, delay, offset, loop, volume, pan); }
    static water(interrupt, delay, offset, loop, volume, pan) { return createjs.Sound.play("water", interrupt, delay, offset, loop, volume, pan); }
}


/***/ }),

/***/ "./src/autogenerated/base.ts":
/*!***********************************!*\
  !*** ./src/autogenerated/base.ts ***!
  \***********************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   base: () => (/* binding */ base)
/* harmony export */ });
// This file is autogenerated by NanoFL
var base;
(function (base) {
    class McBucket extends nanofl.MovieClip {
        constructor() {
            super(nanofl.Player.library.getItem("bucket"));
        }
        get mcNeck() { return this.getChildByName("mcNeck"); }
        get tfLabel() { return this.getChildByName("tfLabel"); }
        get mcForeColor() { return this.getChildByName("mcForeColor"); }
        get mcBox() { return this.getChildByName("mcBox"); }
    }
    base.McBucket = McBucket;
    class Game extends nanofl.MovieClip {
        constructor() {
            super(nanofl.Player.library.getItem("game"));
        }
    }
    base.Game = Game;
    class MusicButton extends nanofl.MovieClip {
        constructor() {
            super(nanofl.Player.library.getItem("musicButton"));
        }
    }
    base.MusicButton = MusicButton;
    class Scene extends nanofl.MovieClip {
        constructor() {
            super(nanofl.Player.library.getItem("scene"));
        }
        get btGotoGame() { return this.getChildByName("btGotoGame"); }
        get btRules() { return this.getChildByName("btRules"); }
        get btGotoOrigin() { return this.getChildByName("btGotoOrigin"); }
        get tfLevel() { return this.getChildByName("tfLevel"); }
        get btNextLevel() { return this.getChildByName("btNextLevel"); }
        get mcTrash() { return this.getChildByName("mcTrash"); }
        get game() { return this.getChildByName("game"); }
        get tfTask() { return this.getChildByName("tfTask"); }
        get mcTap() { return this.getChildByName("mcTap"); }
    }
    base.Scene = Scene;
    class McTrash extends nanofl.MovieClip {
        constructor() {
            super(nanofl.Player.library.getItem("trash"));
        }
    }
    base.McTrash = McTrash;
})(base || (base = {}));


/***/ }),

/***/ "./src/autogenerated/linked-classes.ts":
/*!*********************************************!*\
  !*** ./src/autogenerated/linked-classes.ts ***!
  \*********************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   Game: () => (/* reexport safe */ _Game__WEBPACK_IMPORTED_MODULE_1__.Game),
/* harmony export */   McBucket: () => (/* reexport safe */ _McBucket__WEBPACK_IMPORTED_MODULE_0__.McBucket),
/* harmony export */   McTrash: () => (/* reexport safe */ _McTrash__WEBPACK_IMPORTED_MODULE_4__.McTrash),
/* harmony export */   MusicButton: () => (/* reexport safe */ _MusicButton__WEBPACK_IMPORTED_MODULE_2__.MusicButton),
/* harmony export */   Scene: () => (/* reexport safe */ _Scene__WEBPACK_IMPORTED_MODULE_3__.Scene)
/* harmony export */ });
/* harmony import */ var _McBucket__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ../McBucket */ "./src/McBucket.ts");
/* harmony import */ var _Game__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../Game */ "./src/Game.ts");
/* harmony import */ var _MusicButton__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ../MusicButton */ "./src/MusicButton.ts");
/* harmony import */ var _Scene__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! ../Scene */ "./src/Scene.ts");
/* harmony import */ var _McTrash__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! ../McTrash */ "./src/McTrash.ts");







/***/ })

/******/ 	});
/************************************************************************/
/******/ 	// The module cache
/******/ 	var __webpack_module_cache__ = {};
/******/ 	
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/ 		// Check if module is in cache
/******/ 		var cachedModule = __webpack_module_cache__[moduleId];
/******/ 		if (cachedModule !== undefined) {
/******/ 			return cachedModule.exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = __webpack_module_cache__[moduleId] = {
/******/ 			// no module.id needed
/******/ 			// no module.loaded needed
/******/ 			exports: {}
/******/ 		};
/******/ 	
/******/ 		// Execute the module function
/******/ 		__webpack_modules__[moduleId](module, module.exports, __webpack_require__);
/******/ 	
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/ 	
/************************************************************************/
/******/ 	/* webpack/runtime/define property getters */
/******/ 	(() => {
/******/ 		// define getter functions for harmony exports
/******/ 		__webpack_require__.d = (exports, definition) => {
/******/ 			for(var key in definition) {
/******/ 				if(__webpack_require__.o(definition, key) && !__webpack_require__.o(exports, key)) {
/******/ 					Object.defineProperty(exports, key, { enumerable: true, get: definition[key] });
/******/ 				}
/******/ 			}
/******/ 		};
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/hasOwnProperty shorthand */
/******/ 	(() => {
/******/ 		__webpack_require__.o = (obj, prop) => (Object.prototype.hasOwnProperty.call(obj, prop))
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/make namespace object */
/******/ 	(() => {
/******/ 		// define __esModule on exports
/******/ 		__webpack_require__.r = (exports) => {
/******/ 			if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
/******/ 				Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
/******/ 			}
/******/ 			Object.defineProperty(exports, '__esModule', { value: true });
/******/ 		};
/******/ 	})();
/******/ 	
/************************************************************************/
var __webpack_exports__ = {};
// This entry need to be wrapped in an IIFE because it need to be in strict mode.
(() => {
"use strict";
/*!****************************!*\
  !*** ./src/application.ts ***!
  \****************************/
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   Game: () => (/* reexport safe */ _autogenerated_linked_classes__WEBPACK_IMPORTED_MODULE_0__.Game),
/* harmony export */   McBucket: () => (/* reexport safe */ _autogenerated_linked_classes__WEBPACK_IMPORTED_MODULE_0__.McBucket),
/* harmony export */   McTrash: () => (/* reexport safe */ _autogenerated_linked_classes__WEBPACK_IMPORTED_MODULE_0__.McTrash),
/* harmony export */   MusicButton: () => (/* reexport safe */ _autogenerated_linked_classes__WEBPACK_IMPORTED_MODULE_0__.MusicButton),
/* harmony export */   Scene: () => (/* reexport safe */ _autogenerated_linked_classes__WEBPACK_IMPORTED_MODULE_0__.Scene)
/* harmony export */ });
/* harmony import */ var _autogenerated_linked_classes__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./autogenerated/linked-classes */ "./src/autogenerated/linked-classes.ts");


})();

var __webpack_export_target__ = (window = typeof window === "undefined" ? {} : window);
for(var i in __webpack_exports__) __webpack_export_target__[i] = __webpack_exports__[i];
if(__webpack_exports__.__esModule) Object.defineProperty(__webpack_export_target__, "__esModule", { value: true });
/******/ })()
;