// Generated by Haxe 4.3.3
(function ($hx_exports, $global) { "use strict";
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
var js_injecting_Injector = function() { };
var nanofl_ide_Globals = $hx_exports["Globals"] = function() { };
nanofl_ide_Globals.setInjector = function(_injector) {
	nanofl_ide_Globals.injector = _injector;
};
})(typeof exports != "undefined" ? exports : typeof window != "undefined" ? window : typeof self != "undefined" ? self : this, {});
