// This file is regenerated by NanoFL on every publish.

export class Sounds
{
	static bucket() : HTMLAudioElement { return nanofl.Player.library.getItem("_sounds/sndBucket").play() }
	static music() : HTMLAudioElement { return nanofl.Player.library.getItem("_sounds/sndMusic").play() }
	static tap() : HTMLAudioElement { return nanofl.Player.library.getItem("_sounds/sndTap").play() }
	static trash() : HTMLAudioElement { return nanofl.Player.library.getItem("_sounds/sndTrash").play() }
	static water() : HTMLAudioElement { return nanofl.Player.library.getItem("_sounds/sndWater").play() }
}
