// This file is autogenerated by NanoFL

/// <reference types='nanofl-ts' />

export namespace base
{
	export class MyButton extends nanofl.Button
	{
		constructor() {
			super(nanofl.Player.library.getItem("MainButton"));
		}
	}
}

export class Sounds
{
}
