import { base, Sounds } from './autogenerated';

export class MusicButton extends base.MusicButton
{
	soundLoop : HTMLAudioElement;

    init()
    {
		this.cursor = "pointer";
		this.musicOn();
    }
	
	onMouseUp(e:nanofl.MouseEvent)
	{
        if (this.getBounds().contains(e.localX, e.localY))
		{
			if (this.currentFrame == 1) this.musicOn();
			else                        this.musicOff();
		}
	}
	
	musicOn()
	{
		this.gotoAndStop(0);
		if (this.soundLoop == null)
        {
            this.soundLoop = Sounds.music();
            this.soundLoop.loop = true;
            this.addEventListener("removed", () => this.musicOff());
        }
	}
	
	musicOff()
	{
		this.gotoAndStop(1);
		if (this.soundLoop != null)
        {
    		this.soundLoop.pause();
            this.soundLoop = null;
        }
	}
}
